# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8.0.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19
  build_image:
    docker:
      - image: docker:latest
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: install aws cli
        command: |
          apk add --no-cache --update py-pip
          pip install awscli
    - run:
        name: build image
        command: |
          ${aws ecr get-login --no-include-email --region ap-northeast-1}
          docker build -t ${ECR_DOMAIN}/bulletin-board-image:$CIRCLE_SHA1 -t ${ECR_DOMAIN}/bulletin-board-image:latest
    - run:
        name: Push Docker image
        command: |
          docker push ${ECR_DOMAIN}/bulletin-board-image:$CIRCLE_SHA1
          docker push ${ECR_DOMAIN}/bulletin-board-image:latest
workflows:
  version: 2
  test:
    jobs:
     - build
     - build_image:
        requires: 
          - build
        filters:
          branches:
            only: master
