export const GET_VIDEO_PLAYLIST_START = 'GET_VIDEO_PLAYLIST_START';
export const GET_VIDEO_PLAYLIST_SUCCEED = 'GET_VIDEO_PLAYLIST_SUCCEED';
export const GET_VIDEO_PLAYLIST_FAIL = 'GET_VIDEO_PLAYLIST_FAIL';
